server:
  port: 8100

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: app-bff-payment

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
      autoconfiguration:
        jackson:
          enabled: true
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true
    config:
      enabled: false

  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      FAIL_ON_EMPTY_BEANS: false