server:
  port: 8100

name:
  service:
    repository: app-repository-payment

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-},%X{correlationID:-}] "
  include-application-name: false

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: app-bff-payment
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
      autoconfiguration:
        jackson:
          enabled: true
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true
    config:
      enabled: false


  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      FAIL_ON_EMPTY_BEANS: false